import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const currentYear = new Date().getFullYear();
	return (
		<StoryblokProvider>
			<html lang="en" className={roboto.className}>
				<body className="flex flex-col min-h-screen justify-between">
					{children}
					<footer>All rights reserved © {currentYear} </footer>
				</body>
			</html>
		</StoryblokProvider>
	);
}
