import { Inter, Playfair_Display } from 'next/font/google'
import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { getGlobalConfig } from "@/lib/storyblok"

// Initialize the primary font
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // This is the CSS variable name
  display: 'swap',
})

// Initialize the secondary font
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const config = await getGlobalConfig(); 

export default function RootLayout({ children }) {
	const currentYear = new Date().getFullYear();
	return (
		<StoryblokProvider>
			<html lang="en" className={`${inter.variable} ${playfair.variable}`}>
				<body className="flex flex-col min-h-screen justify-between">
					<Header menuItems={config.header_menu} />
					<main className="flex-grow">{children}</main>
					<footer className="p-4 text-center">
						All rights reserved © {currentYear}
					</footer>
					<Footer menuItems={config.footer_menu} />
				</body>
			</html>
		</StoryblokProvider>
	);
}
